apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  labels:
    app: subscriber
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
      version: v1
  template:
    metadata:
      labels:
        app: subscriber
        version: v1
    spec:
      containers:
        - name: subscriber
          image: gcr.io/coresystem-171219/c24-media:initial
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /google-cloud.json
          args:
            - subscriber
          resources:
            limits:
              cpu: "1"
              memory: "1000M"
            requests:
              cpu: "1"
              memory: "1000M"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader
  labels:
    app: downloader
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloader
      version: v1
  template:
    metadata:
      labels:
        app: downloader
        version: v1
    spec:
      containers:
        - name: downloader
          image: gcr.io/coresystem-171219/c24-media:initial
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /google-cloud.json
          args:
            - downloader
          resources:
            limits:
              cpu: "1"
              memory: "1000M"
            requests:
              cpu: "1"
              memory: "1000M"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcoder
  labels:
    app: transcoder
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcoder
      version: v1
  template:
    metadata:
      labels:
        app: transcoder
        version: v1
    spec:
      containers:
        - name: transcoder
          image: gcr.io/coresystem-171219/c24-media:initial
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /google-cloud.json
          args:
            - transcoder
          resources:
            limits:
              cpu: "1"
              memory: "1000M"
            requests:
              cpu: "1"
              memory: "1000M"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---